language: node_js

node_js:
  - '4.3.2'
  - '6.9.4'

install:
  - npm install

script:
  - npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage